from random import randint

tips = [
    "这日子是越来越有判头了（指判定线",
    "假如，我是说假如，判定线能够自由地动起来…",
    "猜猜你要重新加载多少次才能再看到这条tip￣︶￣",
    "来猜猜看这边有几个有用的信息呢~",
    "你知道吗？其实tips全都是废话（确信",
    "啊！要给你看什么Tip好呢…(翻",
    "突然来了一条消息！          哦这里是tips啊，那没事了",
    "有没有数过这是你第几次看到这条tips呢？",
    "我相信你。",
    "不要在意他人对你说什么，你独一无二，你是你自己的光",
    "江源速报：名人自杀现象异常扩散，知名作家留下诡异遗书",
    "江源速报：知名歌手何琼语于昨夜凌晨意外死亡，凶手仍在追查中",
    "江源速报：警方发表惊人结果，何琼语原系自杀身亡",
    "江源速报：天后横死案新进展，凶手恐为桥民流浪汉",
    "江源速报：三大基地全面开放通行，冰封纪元即将结束？",
    "江源速报：专家呼吁复兴AI产业，以应对劳动力紧缺问题",
    "江源速报：政府出台就业新策，望促进失业人员再就业",
    "江源速报：多地出现无故昏厥人员，卫生部呼吁民众注意饮食健康",
    "江源速报：全球年均温再度上升，重返地表签名破千万",
    "江源速报：群体性臆症爆发，多人自称蜂巢C区存在巨塔",
    "江源速报：巨塔效应急剧化，神秘群体林泊浮出水面",
    "江源速报：上半年人口增长率再创新低，新型受精技术受挫",
    "我被困在林泊百科里了！救命！",
    "像素塔真的存在吗。",
    "对不起，你所拨打的电话号码是空号-Sorry, the number you dialed does not exist",
    "72788433374733678633778263464",
    "Let's! Get! Higher!!!",
    "One! Two! Three! Fire!!!",
    "Hit me with the HARDCORE!!!",
    "E! S! M! Power!",
    "NO ONE YES PIGEONS",
    "Yooooooooooooooooooo",
    "噔噔噔 噔噔 噔噔 噔噔噔噔噔噔",
    "INTeRneT ENERGY -Overdose- ",
    "WHAT DO YOU KNOW WHAT DO YOU PLAY WHAT DO YOU REMEMBER WHAT DO YOU LOVE",
    "This is the story for one character of misery",
    "Funding for this program was made possible by viewers like you",
    "不要喝奇怪的品红色药水！",
    "Tell Me Your Secret",
    "小鸽子们不要挑食哦，不管是烤鸭还是欧芹都要吃~",
    "(Not) Sound Only",
    "Redemption.",
    "小心翼翼千万别被发现",
    "与普遍的看法相反，opia不是一首关于眼病的歌",
    "See You Next Time",
    "φ？拿来吧你！",
    "有一个人前来打歌",
    "阿鸠你又在反复看Tips了哦",
    "手持两把锟斤拷，口中疾呼烫烫烫",
    "热知识：这是一条…烫烫烫烫烫！的热知识。",
    "冷知识：这是一条…啊嚏！…冷知识！",
    "时间滴滴答答在走，这首歌你φ了没有？",
    "上次看到这条Tip还是在上次",
    "你AP了，就一定AP了吧！",
    "高三党，现在，立刻，去给我学习！！！",
    "当你在看这行字的时候 我就知道 你肯定在看这行字",
    "我超，劲爆",
    "AT的意思并不是Anti-Thumb（",
    "EZ是指摁着而非Easy，HD是高清而非Hard，IN是里面而非Insane，AT是位于而非Another，等会我是不是说反了？",
    "分数我所欲也，acc亦我所欲也，若二者不可得兼，多练也。",
    "声音传播需要介质",
    "你打一首歌的时间，鸠已经发现 NaN 个问题了",
    "sudo 板子自己打歌",
    "rks是RankingScore，不是热开水！（认真脸）",
    r"\u70b9\u4e2a\u0053\u0074\u0061\u0072\u5457\u0021",
    "https://github.com/qaqFei/PhigrosPlayer",
    r"\u0071\u0061\u0071\u005f\u0066\u0065\u0069",
    "Tip里可以夹带私货吗? -_-",
    r"\u004d\u0049\u0054 !!",
    "你知道吗, float('nan') != float('nan') 哦",
    "帧率过低时可以尝试开启低分辨率模式哦! (--lowquality)",
    "在一个伸手不见五指的中午...",
    "Ctrl + Alt + R 可重开哦!",
    "本项目是使用MIT协议开源的哦!",
    "cjb, 你食不食有病! -- cbszx... -> ed is (?1115)",
    "↑↑↑ hen un ing! // -> 看看源码... (_-_)",
    "[0] => s, u un ing! <- 也食油饼吧~!   (Tip里不可以带私人恩怨哦! --- 不",
    "(╯‵□′)╯",
    "700 * 0.9 = 630 // 有希望! 但是 ...?-100?or50x 相比之下...",
    "... 你怎么能不写注释呢?! -- 就不写!"
]

def get_tip():
    return tips[randint(0, len(tips) - 1)]